[features]
seeds = false
skip-lint = false
[programs.devnet]
counter_solana = "Hs2cnurfstPr7wvYzcJo1soZu6DPbewh6cFfzWqDHLvU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dhruvdabhi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
